### ISSUE TITLE
Support npm script preversion, version, and postversion

### ISSUE THREAD

**Issue by Harris-Miller** [BigstickCarpet/version-bump-prompt#2]
I've begun using this module as a replacement for `npm version`, but what I'm missing is the auto running npm scripts when I use `npm version` (a la: https://docs.npmjs.com/cli/version)

Be great if running them could be added in the same order of operation. I'm willing to give that implementation a shot too, let me know if you want me to start investigating

**Comment by JamesMessinger** [comment]
That's a great idea!  I don't have the spare time to implement it right now, but I'll leave this issue open as a to-do item and reminder.  

In the meantime, if you want to add this, I'll gladly review a PR.  The code already contains an [`exec()` function](https://github.com/BigstickCarpet/version-bump-prompt/blob/master/lib/index.js#L168-L189) for running `git` commands.  It shouldn't be too hard to make it run the `npm run preversion` and `npm run postversion` commands too.

**Comment by webuniverseio** [comment]
It is not that easy to use exec to run npm, since on windows it is represented as a `.bat` file and libuv (that is used by spawn) has a ~1.5 years old bug with `.bat` and `.cmd` files... https://github.com/nodejs/node-v0.x-archive/issues/25330, https://github.com/libuv/libuv/pull/358

I'm trying to see how that can be worked around, ideally by avoiding OS sniffing.

**Comment by webuniverseio** [comment]
Created #17
