### ISSUE TITLE
All occurences of old version are replaced in files instead of only the first

### ISSUE THREAD

**Issue by fbrun** [BigstickCarpet/version-bump-prompt#22]
Hi,

In my package.json (and others files passed to bump command), there are some dependencies like `"cordova-plugin-add-swift-support": "1.7.0",` in it.

When i bump with `bump --prompt --tag --push --all --grep config.xml` for new value at 1.7.1 for example, if my actual package version is the same as dependencies versions (exemple 1.7.0), then all occurences are replaces in files instead of only the first value (example in package.json : `"version": "1.7.0",`).
So when bump is finished, the dependencie is also at the new version `"cordova-plugin-add-swift-support": "1.7.1",`, altough it must not be !

A correction for this will be to replace  the line 162 in lib/index.js: `let oldVersionPattern = new RegExp(oldVersion.replace(/\./g, '\\.'), 'g');`
with `let oldVersionPattern = new RegExp(oldVersion.replace(/./g, '\.'));`
The new code replace only the first occurence of old version in any files changing by bump command.

What do you think ?

**Comment by JamesMessinger** [comment]
The `grep` option is intended to be used for things like ReadMe files, license files, etc. where you know the contents of the file and can be relatively certain that there won't be any conflicts.  I don't recommend using it for files that contain many different version numbers that could possibly conflict.

Replacing a single instance of the version number rather than all instances doesn't really fix the problem, since it relies on the assumption that the intended version number will always come first. It's also common for the `grep` option to be used in files where the version number may be repeated many times.

**Comment by fbrun** [comment]
i agree but the package.json is not use with --grep option (i don't mention it in my bump command).
It's one of the file automatically modified.

For the confix.xml used with --grep option, it's a file generate with ionic (https://ionicframework.com/), which use it for the app version (in the widget balise). It's contains some dependencies package too.
I use it in args to keep it in sync with package.json for the app version/npm version.

There is an exemple of what config.xml looks like on https://github.com/ionic-team/ionic-conference-app/blob/master/config.xml

Maybe we can imagine a new param in command bump to specifiy for each file to replace if it needs to change only first occurnce or all ?

**Comment by JamesMessinger** [comment]
I just released [**version 5.0.0**](https://github.com/JS-DevTools/version-bump-prompt/blob/master/CHANGELOG.md), which supports [custom behavior for different file names](https://github.com/JS-DevTools/version-bump-prompt/blob/8ae1816396ba2fe17f04707c64cd322f469dad58/src/update-files.ts#L41-L49).  So it would now be pretty trivial to add special behavior for the `config.xml` file.  I'd gladly accept a PR if anybody is interested in submitting one.
