### ISSUE TITLE
Can you add a variable for the version in the commit message?

### ISSUE THREAD

**Issue by RTSchriner** [BigstickCarpet/version-bump-prompt#29]
Can you add a variable for the version in the commit message?

`npm version` does this. See https://docs.npmjs.com/cli/version.html

>If supplied with -m or --message config option, npm will use it as a commit message when creating a version commit. If the message config contains %s then that will be replaced with the resulting version number. For example: `npm version patch -m "Upgrade to %s for reasons"`

So`%s` becomes the version - `bump --premajor --lock --commit "release %s to the wild"`

Thanks!

**Comment by JamesMessinger** [comment]
The `--commit` option allows you to specify a custom commit message.  The version number is appended to your message, so if you do `bump --commit "Upgrading to v"` then the commit message will be `Updating to vX.X.X`.

I do like the idea of being able to put the version number anywhere in the message via a placeholder.  And I think I can add that in a backward-compatible way, too.  Basically, if the message contains the placeholder, then replace it with the version number.  Otherwise, just append the version number.

**Comment by RTSchriner** [comment]
Thanks for taking the time to respond!

> The version number is appended to your message...
Ah, I didn't realize the that. That'll actually work for what I need then.

Thank you, very much!

**Comment by JamesMessinger** [comment]
I just released [**version 5.0.0**](https://github.com/JS-DevTools/version-bump-prompt/blob/master/CHANGELOG.md), which resolves this issue.
